#!/usr/bin/env tsx

import { readdirSync, statSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs'
import { join, relative, dirname, sep } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const rootDir = join(__dirname, '..')
const pagesDir = join(rootDir, 'src', 'pages')
const outputFile = join(rootDir, 'src', 'lib', 'pageRegistry.ts')

interface PageFile {
  path: string
  relativePath: string
  importPath: string
  varName: string
}

function getAllPageFiles(dir: string, baseDir: string = dir): PageFile[] {
  const files: PageFile[] = []

  if (!existsSync(dir)) {
    console.warn(`Pages directory does not exist: ${dir}`)
    return files
  }

  const entries = readdirSync(dir)

  for (const entry of entries) {
    const fullPath = join(dir, entry)
    const stat = statSync(fullPath)

    if (stat.isDirectory()) {
      files.push(...getAllPageFiles(fullPath, baseDir))
    } else if (entry.endsWith('.tsx') && entry !== 'index.tsx') {
      const relativePath = relative(baseDir, fullPath)
      // Convert path to import path (forward slashes, no extension)
      const importPath = '@/pages/' + relativePath
        .replace(/\\/g, '/')
        .replace(/\.tsx$/, '')

      // Create a valid variable name from the file path
      const varName = relativePath
        .replace(/\.tsx$/, '')
        .replace(/[\/\\]/g, '_')
        .replace(/[^a-zA-Z0-9_]/g, '')

      files.push({
        path: fullPath,
        relativePath,
        importPath,
        varName,
      })
    }
  }

  return files
}

function hasMetadataExport(filePath: string): boolean {
  const content = readFileSync(filePath, 'utf-8')
  // Check if file exports a metadata constant
  return /export\s+const\s+metadata\s*[:=]/.test(content)
}

function generateRegistry() {
  console.log('🔍 Scanning for page files...')

  const pageFiles = getAllPageFiles(pagesDir)
    .filter(file => hasMetadataExport(file.path))

  console.log(`📄 Found ${pageFiles.length} page files with metadata`)

  if (pageFiles.length === 0) {
    console.warn('⚠️  No pages found. Creating empty registry.')
  }

  // Generate imports
  const imports = pageFiles
    .map(file => `import * as ${file.varName} from '${file.importPath}'`)
    .join('\n')

  // Generate pages array
  const pagesArray = pageFiles
    .map(file => `  { ...${file.varName}.metadata, component: ${file.varName}.default }`)
    .join(',\n')

  // Generate the registry file
  const registryContent = `// This file is auto-generated by scripts/generate-registry.ts
// Do not edit manually - your changes will be overwritten

import { PageMetadata } from '@/types/page'

${imports}

export const pages: PageMetadata[] = [
${pagesArray}
]

export function getPageById(id: string): PageMetadata | undefined {
  return pages.find(page => page.id === id)
}

export function getPageByPath(path: string): PageMetadata | undefined {
  return pages.find(page => page.path === path)
}

export function getPagesByCategory(category: string): PageMetadata[] {
  return pages.filter(page => page.category === category)
}

export function getAllCategories(): string[] {
  const categories = new Set(pages.map(page => page.category))
  return Array.from(categories)
}
`

  // Ensure lib directory exists
  const libDir = dirname(outputFile)
  if (!existsSync(libDir)) {
    mkdirSync(libDir, { recursive: true })
  }

  writeFileSync(outputFile, registryContent, 'utf-8')

  console.log(`✅ Generated registry at: ${relative(rootDir, outputFile)}`)
  console.log(`📊 Registered ${pageFiles.length} pages`)
}

try {
  generateRegistry()
} catch (error) {
  console.error('❌ Error generating registry:', error)
  process.exit(1)
}
